var drawData = {
  "name": "draw",
  "version": "0.0.1",
  "data": {
    "svg-path": "images/svg/",
    "icons": [{
      "name": "pentagram",
      "class": "icon-1",
      "svg": "1.svg",
      "title": "五角星"
    }, {
      "name": "hollow-pentagram",
      "class": "icon-2",
      "svg": "2.svg",
      "title": "空心五角星"
    }, {
      "name": "warehouse",
      "class": "icon-3",
      "svg": "3.svg",
      "title": "仓库"
    }, {
      "name": "boiler-room",
      "class": "icon-4",
      "svg": "4.svg",
      "title": "锅炉房"
    }, {
    	"name": "samplingPoint",
    	"class": "icon-5",
        "svg": "5.svg",
        "title": "采样点"
    }, {
    	"name": "eclipse",
    	"class": "icon-6",
        "svg": "6.svg"
    }, {
    	"name": "oil-depot",
    	"class": "icon-7",
        "svg": "7.svg",
        "title": "油库"
    }, {
    	"name": "radioactive-pollution-source",
    	"class": "icon-8",
        "svg": "8.svg",
        "title": "放射性污染源"
    }, {
    	"name": "hollow-trapezoid",
    	"class": "icon-9",
        "svg": "9.svg"
    }, {
    	"name": "trapezoid",
    	"class": "icon-10",
        "svg": "10.svg"
    }, {
    	"name": "triangle",
    	"class": "icon-11",
        "svg": "11.svg"
    }, {
    	"name": "hollow-triangle",
    	"class": "icon-12",
        "svg": "12.svg"
    }, {
    	"name": "rectangle",
    	"class": "icon-13",
        "svg": "13.svg"
    }, {
    	"name": "sewage-disposal",
    	"class": "icon-15",
        "svg": "15.svg",
        "title": "污水处理"
    }, {
    	"name": "water-tower",
    	"class": "icon-16",
        "svg": "16.svg",
        "title": "水塔"
    }, {
    	"name": "manufacturing-shop",
    	"class": "icon-17",
        "svg": "17.svg",
        "title": "生产车间"
    }, {
    	"name": "standard-discharge-port",
    	"class": "icon-18",
        "svg": "18.svg",
        "title": "标准排口"
    }, {
    	"name": "drain-port",
    	"class": "icon-19",
        "svg": "19.svg",
        "title": "漏排口"
    }, {
    	"name": "straight-line",
    	"class": "icon-20",
        "svg": "20.svg",
        "title": "直排口"
    }, {
    	"name": "water-wells-sampling-points",
    	"class": "icon-21",
        "svg": "21.svg",
        "title": "雨水井采样点"
    }, {
    	"name": "test1",
    	"class": "icon-22",
        "svg": "22.svg"
    }, {
    	"name": "monitoring-points",
    	"class": "icon-23",
        "svg": "23.svg",
        "title": "监控点"
    }, {
    	"name": "total-discharge-port",
    	"class": "icon-24",
        "svg": "24.svg",
        "title": "总排口"
    }, {
    	"name": "test2",
    	"class": "icon-25",
        "svg": "25.svg"
    }, {
    	"name": "chimney",
    	"class": "icon-26",
        "svg": "26.svg"
    }, {
    	"name": "seepage-wells",
    	"class": "icon-27",
        "svg": "27.svg",
        "title": "渗坑、渗井"
    }, {
    	"name": "solid-waste-outfall",
    	"class": "icon-28",
        "svg": "28.svg",
        "title": "固体废物排放口"
    }, {
    	"name": "concentrically",
    	"class": "icon-29",
        "svg": "29.svg"
    }, {
    	"name": "electromagnetic-radiation",
    	"class": "icon-30",
        "svg": "30.svg",
        "title": "电磁辐射源"
    }, {
    	"name": "test4",
    	"class": "icon-31",
        "svg": "31.svg"
    }, {
    	"name": "sewage-treatment-plant",
    	"class": "icon-32",
        "svg": "32.svg",
        "title": "污水处理装置"
    }, {
    	"name": "tank area",
    	"class": "icon-33",
        "svg": "33.svg",
        "title": "储罐区"
    }, {
    	"name": "noise-source",
    	"class": "icon-34",
        "svg": "34.svg",
        "title": "噪声源"
    }, {
    	"name": "test6",
    	"class": "icon-35",
        "svg": "35.svg"
    }, {
    	"name": "sewers",
    	"class": "icon-36",
        "svg": "36.svg",
        "title": "污水管道及流向"
    }, {
    	"name": "close",
    	"class": "icon-37",
        "svg": "37.svg",
        "title": "关闭"
    }, {
    	"name": "compass",
    	"class": "icon-38",
        "svg": "38.svg",
        "title": "方向北"
    }]
  }
}
